# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']    # ← quote this so it's not interpreted as 3.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

      - name: Create & activate virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -e .
          pip install pre-commit
          pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
